/*
* <-- Coin-Op Collection -->
* https://coinopcollection.org
* https://github.com/Coin-OpCollection/
*
* Author: atrac17 (https://twitter.com/_atrac17)
* Copyright © 2026 Coin-Op Collection
*
* This work is licensed under the Creative Commons Attribution-NonCommercial 4.0 International License.
* To view a copy of this license, visit http://creativecommons.org/licenses/by-nc/4.0/.
*
* You may use, share, and modify this code for non-commercial purposes, provided that proper credit is given.
*/

//============================================================================
//  Agnostic VGM playback testbench for the AY-3-8910 PSG implementation.
//
//  Reads a combined playlist hex file (generated by vgm2hex.py) containing
//  any number of tracks with per-track AY clock configuration. No hardcoded
//  filenames, track counts, or clock values. Outputs sequentially numbered
//  raw PCM files that wav_batch.py converts to named WAV files using the
//  tracklist index.
//
//  Playlist format (32-bit hex words loaded via $readmemh):
//    3_CC_CC_CC  = Track start (lower 24 bits = CEN ticks per sample)
//    1_RR_00_VV  = Write register RR with value VV
//    2_WW_WW_WW  = Wait WWWWWW samples (at 44100 Hz)
//    0_00_00_00  = End of track
//    F_00_00_00  = End of playlist
//
//  Usage:
//    python scripts/vgm2hex.py
//    vlog tb_x8910_vgm.v ../hdl/*.v
//    vsim -c tb_x8910_vgm -do "run -all; quit -f"
//    python scripts/wav_batch.py
//
//  Reference: GI AY-3-8910/8912 PSG Data Manual
//             VGM file format specification
//============================================================================
`timescale 1ns/1ps

module tb_x8910_vgm;

//=========================================================================
// Configuration
//=========================================================================
localparam MAX_CMDS = 262144;

//=========================================================================
// Test Signals
//=========================================================================
reg        clk;
reg        cen;
reg        reset;
reg        a0;
reg        wr;
reg        rd;
reg  [7:0] din;
wire [7:0] dout;
wire [7:0] sndout;

//=========================================================================
// DUT Instantiation
//=========================================================================
x8910 uut (
    .clk    ( clk    ),
    .cen    ( cen    ),
    .reset  ( reset  ),
    .a0     ( a0     ),
    .wr     ( wr     ),
    .rd     ( rd     ),
    .din    ( din    ),
    .dout   ( dout   ),
    .sndout ( sndout )
);

//=========================================================================
// Clock Generation
//=========================================================================
initial clk = 0;
always #5 clk = ~clk;

//=========================================================================
// Helper Tasks
//=========================================================================
task cycle;
    begin
        @(posedge clk);
        #1 cen = 1;
        @(posedge clk);
        #1 cen = 0;
    end
endtask

task write_reg;
    input [3:0] reg_addr;
    input [7:0] data;
    begin
        @(posedge clk);
        #1;
        a0 = 1'b0;
        din = {4'd0, reg_addr};
        wr = 1'b1;
        @(posedge clk);
        #1;
        wr = 1'b0;

        @(posedge clk);
        #1;
        a0 = 1'b1;
        din = data;
        wr = 1'b1;
        @(posedge clk);
        #1;
        wr = 1'b0;
        a0 = 1'b0;
    end
endtask

task reset_system;
    begin
        reset = 1;
        cen = 0;
        a0 = 0;
        wr = 0;
        rd = 0;
        din = 8'h00;
        #100;
        reset = 0;
        #50;
        cycle();
    end
endtask

//=========================================================================
// Playlist Memory and Playback
//=========================================================================
reg [31:0] playlist [0:MAX_CMDS-1];

integer fd;
integer cmd_idx;
integer track_num;
integer total_samples;
integer cen_per_sample;
integer wait_samples;
integer cen_count;
integer s;
integer done;
integer track_active;

reg [3:0]  cmd_type;
reg [1023:0] raw_filename;

initial begin
    $display("=============================================================");
    $display("  AY-3-8910 VGM Playlist Testbench");
    $display("=============================================================\n");

    $readmemh("output/vgm_hex/playlist.hex", playlist);

    cmd_idx = 0;
    track_num = 0;
    done = 0;
    fd = 0;

    while(!done && cmd_idx < MAX_CMDS) begin
        cmd_type = playlist[cmd_idx][31:28];

        case(cmd_type)
            // End of playlist
            4'hF: begin
                done = 1;
            end

            // Track start marker
            4'h3: begin
                track_num = track_num + 1;
                cen_per_sample = playlist[cmd_idx][27:0];
                $display("  [Track %0d] CEN/sample=%0d", track_num, cen_per_sample);

                $sformat(raw_filename, "output/wav/track_%02d.raw", track_num);
                fd = $fopen(raw_filename, "wb");

                if(fd == 0) begin
                    $display("    ERROR: Could not open output file");
                    // Skip to next track or end
                    while(cmd_idx < MAX_CMDS && playlist[cmd_idx][31:28] != 4'h0)
                        cmd_idx = cmd_idx + 1;
                end else begin
                    reset_system();
                    total_samples = 0;
                    track_active = 1;

                    while(track_active && cmd_idx < MAX_CMDS - 1) begin
                        cmd_idx = cmd_idx + 1;
                        cmd_type = playlist[cmd_idx][31:28];

                        case(cmd_type)
                            // End of track
                            4'h0: begin
                                // Silence tail
                                write_reg(4'd8, 8'h00);
                                write_reg(4'd9, 8'h00);
                                write_reg(4'd10, 8'h00);
                                for(s = 0; s < 256; s = s + 1) begin
                                    for(cen_count = 0; cen_count < cen_per_sample; cen_count = cen_count + 1)
                                        cycle();
                                    $fwrite(fd, "%c", sndout);
                                    total_samples = total_samples + 1;
                                end

                                $fclose(fd);
                                fd = 0;
                                $display("    -> %0d samples (%0d.%0d sec)",
                                         total_samples, total_samples / 44100,
                                         (total_samples % 44100) * 10 / 44100);
                                track_active = 0;
                            end

                            // Register write
                            4'h1: begin
                                write_reg(playlist[cmd_idx][19:16], playlist[cmd_idx][7:0]);
                            end

                            // Wait
                            4'h2: begin
                                wait_samples = playlist[cmd_idx][27:0];
                                for(s = 0; s < wait_samples; s = s + 1) begin
                                    for(cen_count = 0; cen_count < cen_per_sample; cen_count = cen_count + 1)
                                        cycle();
                                    $fwrite(fd, "%c", sndout);
                                    total_samples = total_samples + 1;
                                end
                            end

                            default: ;
                        endcase
                    end
                end
            end

            default: ;
        endcase

        cmd_idx = cmd_idx + 1;
    end

    $display("\n=============================================================");
    $display("  Playlist complete: %0d tracks", track_num);
    $display("  Run: python scripts/wav_batch.py");
    $display("=============================================================\n");

    $stop;
end

endmodule
